namespace Esprima.Utils.Jsx;

[AutoGeneratedAstVisitor(VisitorType = typeof(IJsxAstVisitor), TargetVisitorFieldName = "_visitor")]
public partial class JsxAstVisitor : AstVisitor, IJsxAstVisitor
{
    /// <summary>
    /// Creates an <see cref="IJsxAstVisitor"/> instance which can be used for working around multiple inheritance:
    /// the returned instance re-routes visitations of JSX nodes to the specified <paramref name="visitor"/>,
    /// thus it can be used for emulating base class method calls.
    /// </summary>
    public static IJsxAstVisitor CreateJsxVisitorFor<TVisitor>(TVisitor visitor)
        where TVisitor : AstVisitor, IJsxAstVisitor
    {
        return new JsxAstVisitor(visitor);
    }

    private readonly AstVisitor _visitor;

    public JsxAstVisitor()
    {
        _visitor = this;
    }

    private JsxAstVisitor(AstVisitor visitor)
    {
        _visitor = visitor;
    }
}
