//HintName: AutoGeneratedAstVisitorAttribute.g.cs
#nullable enable

namespace Esprima.Utils;

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
internal class AutoGeneratedAstVisitorAttribute : Attribute
{
    public Type? VisitorType { get; set; }
    public string? TargetVisitorFieldName { get; set; }
    public string? BaseVisitorFieldName { get; set; }
}
