name: Build

on:

  pull_request:
    branches: [ main, release/1.x, release/2.x ]
    paths-ignore:
    - 'doc/**'
    - '*.md'

jobs:

  windows:
    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Test
      run: dotnet test --configuration Release

  linux:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Test
      run: dotnet test --configuration Release
