name: Build

on:

  pull_request:
    branches: [ main, release/1.x, release/2.x ]
    paths-ignore:
    - 'doc/**'
    - '*.md'

jobs:

  windows:
    runs-on: windows-2022
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Test
      run: dotnet test --configuration Release

    - name: Parse Test262 ECMAScript Test Suite
      run: dotnet run -c Release --project test/Esprima.Tests.Test262/Esprima.Tests.Test262.csproj


  linux:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - name: Test
      run: dotnet test --configuration Release

    - name: Parse Test262 ECMAScript Test Suite
      run: dotnet run -c Release --project test/Esprima.Tests.Test262/Esprima.Tests.Test262.csproj
