name: Build

on:

  pull_request:
    branches: [ main, release/1.x, release/2.x ]
    paths-ignore:
    - 'doc/**'
    - '*.md'

jobs:

  windows:
    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate test cases
      working-directory: ./test/Esprima.Tests.Test262
      run: dotnet tool restore && dotnet test262 generate && dotnet run -c Release

    - name: Test
      run: dotnet test --configuration Release --logger GitHubActions

  linux:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - name: Generate test cases
      working-directory: ./test/Esprima.Tests.Test262
      run: dotnet tool restore && dotnet test262 generate && dotnet run -c Release -- --update-allow-list

    - name: Test
      run: dotnet test --configuration Release --framework net6.0 --logger GitHubActions
