name: Publish on MyGet

on:

  push:
    branches: [ main ]
    paths-ignore:
    - 'doc/**'
    - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          3.1.x
          6.0.x

    - name: Generate test cases
      working-directory: ./test/Esprima.Tests.Test262
      run: dotnet tool restore && dotnet test262 generate && dotnet run -c Release -- --update-allow-list

    - name: Test
      run: dotnet test --configuration Release --logger "GitHubActions;report-warnings=false"

    - name: Pack with dotnet
      run: dotnet pack --output artifacts --configuration Release -p:PackageVersion=3.0.0-preview-$GITHUB_RUN_NUMBER

    - name: Push with dotnet
      run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.MYGET_API_KEY }} --skip-duplicate --source https://www.myget.org/F/esprimadotnet/api/v2/package
